//! Build-time wire identity (magics + HKDF/HMAC domains).
//! Generated by `build.rs` from `WIRE_SEED` (must match server).

include!(concat!(env!("OUT_DIR"), "/wire_ids.rs"));

// Aliases used across the crate
pub const FRAG_MAGIC: [u8; 4] = MAGIC_FRAG;
pub const JOB_MAGIC: [u8; 4] = MAGIC_JOB;
pub const PKG_MAGIC: [u8; 4] = MAGIC_PKG;
